---
- name: This is the fifth network playbook
  # the line below uses regex to parse the inventory file
  hosts: ~^arista
  # gather_facts ALWAYS runs setup.py (server module)
  gather_facts: no  # v2.5=< no is default is network_cli is selected for connection
                    # if turned to yes you'll collect info about the local host  =o(
  tasks:
  # if we run this and have gather_facts set to no, then ansible_facts will be agout our network devs
  - name: Harveting Arista
    eos_facts:
    when: ansible_network_os == 'eos'
  - name: Push to Local sustem -- by special tag request only
    copy:
     # use the to_nice_json filter to display pretty json output
     content: "{{ ansible_facts | to_nice_json }}"
     dest: "/home/student/mycode/{{ inventory_hostname }}.txt"
     # the inventory_hostname variable always resolves to the current host being iterated against
    tags:
     - never
     - grabfacts

    # Precheck conditional number of interfaces
  - fail:
     msg: "FAILED. DOH, this device lacks the correct number of ports"
    when: ansible_facts.net_interfaces|length !=13
   # Firmware precheck on correct major and minor versions
  - fail:
     msg: "FAIL. This Sh** is old! Update it damn."
    when: "'4.17' not in ansible_facts.net_version"
