---
- name: This is the Fourth network playook example, hA hA Ha hA
  # The line below uses regex to parse the inventory file
  hosts: ~^arista
  # gather_facts ALWAYS runs setup.py (server module)
  gather_facts: no  # 2.5=< is default if network_cli is selected for connection
                    # if turned to yes you'll collect info aout the local host  =o(
  tasks:
  # if we run this and have gather_facts set to no, then ansible_facts will be bout our network devs
  - name: Harvest Arista facts
    eos_facts:
    when: ansible_network_os == 'eos'
  - name: Push to the local system -- by special tag request ONLY use you brain!!!
    copy:
      # use the to_nice_json filter to display pretty json output
      content: "{{ ansible_facts | to_nice_json }}"
      dest: "/home/student/mycode/{{ inventory_hostname }}.txt"
      # the inventory_host variable always resolves to the current host being iterate against
    tags:
      - never
      - grabfacts
    # Precheck conditional number of interfaces
  - fail:
     msg: "YOU FAILED! Network device lacks the correct number of interfaces, Where did you learn to count?!?!?"
    when: ansible_facts.net_interfaces|length !=13
