---
- name: OK, OK, This is the final network example. I SWEAR!
  # The line below uses regex to parse the inventory file
  hosts: ~^arista
  # gather_facts ALWAYS runs setup.py (server module)
  gather_facts: no # v2.5=< no is default if network_cli is selected for connection
                   # if turned to yes you'll collect info about the local host =o(
  vars:
    switchint: 13
    switchver: "4.17"
  tasks:
  # if we run this and have gather_facts set to no, then ansible_facts will be about our network devices
  - name: Hungry Hungry Hippo Arista facts
    eos_facts:
    when: ansible_network_os == 'eos'
  - name: Vomit the data to local system
    copy:
      # use the to_nice_json to display pretty json ouput
      content: "{{ ansible_facts | to_nice_json }}"
      dest: "/home/student/mycode/{{ inventory_hostname }}.txt"
      # the inventory_hostname variable always resolve to the current host being iterated against
    tags:
      - never
      - grabfacts
    # Precheck conditional number of interfaces
  - fail:
     msg: "FAIL! Ha hA Ha hA, where did you learn how to count?"
    when: ansible_facts.net_interfaces|length != switchint
    # Firmware check software version
  - fail:
     msg: "FAIL! OMG this is some of the oldest SH** I have ever seen!"
    when: "switchver not in ansible_facts.net_version"
